/* Auto-generated: export-only stubs for EOS funcs the committed
 * stubs_generated.c predated (EOS SDK 1.16: Achievements V2, AntiCheatClient,
 * RTCAudio device mgmt, Leaderboards). Generic void* params (ABI-safe on x64;
 * args ignored) so we avoid the internally-inconsistent function headers and
 * any prototype conflict. Exported so UE5 EOS module delay-loads never fail
 * with 0xc06d007f. Generated by /tmp/gen_missing.py. */
#include "eos/eos_sdk.h"
#include "internal/logging.h"

EOS_DECLARE_FUNC(EOS_NotificationId) EOS_Achievements_AddNotifyAchievementsUnlocked(void* a0, void* a1, void* a2, void* a3) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; (void)a2; (void)a3; return 0; }
EOS_DECLARE_FUNC(EOS_EResult) EOS_Achievements_CopyAchievementDefinitionByAchievementId(void* a0, void* a1, void* a2) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; (void)a2; return EOS_NotConfigured; }
EOS_DECLARE_FUNC(EOS_EResult) EOS_Achievements_CopyAchievementDefinitionV2ByAchievementId(void* a0, void* a1, void* a2) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; (void)a2; return EOS_NotConfigured; }
EOS_DECLARE_FUNC(EOS_EResult) EOS_Achievements_CopyPlayerAchievementByAchievementId(void* a0, void* a1, void* a2) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; (void)a2; return EOS_NotConfigured; }
EOS_DECLARE_FUNC(EOS_EResult) EOS_Achievements_CopyUnlockedAchievementByAchievementId(void* a0, void* a1, void* a2) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; (void)a2; return EOS_NotConfigured; }
EOS_DECLARE_FUNC(EOS_EResult) EOS_Achievements_CopyUnlockedAchievementByIndex(void* a0, void* a1, void* a2) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; (void)a2; return EOS_NotConfigured; }
EOS_DECLARE_FUNC(uint32_t) EOS_Achievements_GetUnlockedAchievementCount(void* a0, void* a1) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; return 0; }
EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatClient_AddExternalIntegrityCatalog(void* a0, void* a1) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; return EOS_NotConfigured; }
EOS_DECLARE_FUNC(EOS_NotificationId) EOS_AntiCheatClient_AddNotifyClientIntegrityViolated(void* a0, void* a1, void* a2, void* a3) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; (void)a2; (void)a3; return 0; }
EOS_DECLARE_FUNC(EOS_NotificationId) EOS_AntiCheatClient_AddNotifyMessageToPeer(void* a0, void* a1, void* a2, void* a3) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; (void)a2; (void)a3; return 0; }
EOS_DECLARE_FUNC(EOS_NotificationId) EOS_AntiCheatClient_AddNotifyMessageToServer(void* a0, void* a1, void* a2, void* a3) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; (void)a2; (void)a3; return 0; }
EOS_DECLARE_FUNC(EOS_NotificationId) EOS_AntiCheatClient_AddNotifyPeerActionRequired(void* a0, void* a1, void* a2, void* a3) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; (void)a2; (void)a3; return 0; }
EOS_DECLARE_FUNC(EOS_NotificationId) EOS_AntiCheatClient_AddNotifyPeerAuthStatusChanged(void* a0, void* a1, void* a2, void* a3) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; (void)a2; (void)a3; return 0; }
EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatClient_BeginSession(void* a0, void* a1) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; return EOS_NotConfigured; }
EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatClient_EndSession(void* a0, void* a1) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; return EOS_NotConfigured; }
EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatClient_GetProtectMessageOutputLength(void* a0, void* a1, void* a2) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; (void)a2; return EOS_NotConfigured; }
EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatClient_PollStatus(void* a0, void* a1, void* a2, void* a3) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; (void)a2; (void)a3; return EOS_NotConfigured; }
EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatClient_ProtectMessage(void* a0, void* a1, void* a2, void* a3) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; (void)a2; (void)a3; return EOS_NotConfigured; }
EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatClient_ReceiveMessageFromPeer(void* a0, void* a1) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; return EOS_NotConfigured; }
EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatClient_ReceiveMessageFromServer(void* a0, void* a1) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; return EOS_NotConfigured; }
EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatClient_RegisterPeer(void* a0, void* a1) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; return EOS_NotConfigured; }
EOS_DECLARE_FUNC(void) EOS_AntiCheatClient_RemoveNotifyClientIntegrityViolated(void* a0, void* a1) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; }
EOS_DECLARE_FUNC(void) EOS_AntiCheatClient_RemoveNotifyMessageToPeer(void* a0, void* a1) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; }
EOS_DECLARE_FUNC(void) EOS_AntiCheatClient_RemoveNotifyMessageToServer(void* a0, void* a1) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; }
EOS_DECLARE_FUNC(void) EOS_AntiCheatClient_RemoveNotifyPeerActionRequired(void* a0, void* a1) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; }
EOS_DECLARE_FUNC(void) EOS_AntiCheatClient_RemoveNotifyPeerAuthStatusChanged(void* a0, void* a1) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; }
EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatClient_Reserved01(void* a0, void* a1, void* a2) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; (void)a2; return EOS_NotConfigured; }
EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatClient_UnprotectMessage(void* a0, void* a1, void* a2, void* a3) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; (void)a2; (void)a3; return EOS_NotConfigured; }
EOS_DECLARE_FUNC(EOS_EResult) EOS_AntiCheatClient_UnregisterPeer(void* a0, void* a1) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; return EOS_NotConfigured; }
EOS_DECLARE_FUNC(EOS_NotificationId) EOS_RTCAudio_AddNotifyAudioOutputState(void* a0, void* a1, void* a2, void* a3) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; (void)a2; (void)a3; return 0; }
EOS_DECLARE_FUNC(EOS_EResult) EOS_RTCAudio_CopyInputDeviceInformationByIndex(void* a0, void* a1, void* a2) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; (void)a2; return EOS_NotConfigured; }
EOS_DECLARE_FUNC(EOS_EResult) EOS_RTCAudio_CopyOutputDeviceInformationByIndex(void* a0, void* a1, void* a2) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; (void)a2; return EOS_NotConfigured; }
EOS_DECLARE_FUNC(uint32_t) EOS_RTCAudio_GetInputDevicesCount(void* a0, void* a1) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; return 0; }
EOS_DECLARE_FUNC(uint32_t) EOS_RTCAudio_GetOutputDevicesCount(void* a0, void* a1) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; return 0; }
EOS_DECLARE_FUNC(void) EOS_RTCAudio_QueryInputDevicesInformation(void* a0, void* a1, void* a2, void* a3) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; (void)a2; (void)a3; }
EOS_DECLARE_FUNC(void) EOS_RTCAudio_QueryOutputDevicesInformation(void* a0, void* a1, void* a2, void* a3) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; (void)a2; (void)a3; }
EOS_DECLARE_FUNC(EOS_EResult) EOS_RTCAudio_RegisterPlatformAudioUser(void* a0, void* a1) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; return EOS_NotConfigured; }
EOS_DECLARE_FUNC(void) EOS_RTCAudio_RegisterPlatformUser(void* a0, void* a1, void* a2, void* a3) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; (void)a2; (void)a3; }
EOS_DECLARE_FUNC(void) EOS_RTCAudio_RemoveNotifyAudioOutputState(void* a0, void* a1) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; }
EOS_DECLARE_FUNC(EOS_EResult) EOS_RTCAudio_SendAudio(void* a0, void* a1) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; return EOS_NotConfigured; }
EOS_DECLARE_FUNC(void) EOS_RTCAudio_SetInputDeviceSettings(void* a0, void* a1, void* a2, void* a3) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; (void)a2; (void)a3; }
EOS_DECLARE_FUNC(void) EOS_RTCAudio_SetOutputDeviceSettings(void* a0, void* a1, void* a2, void* a3) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; (void)a2; (void)a3; }
EOS_DECLARE_FUNC(EOS_EResult) EOS_RTCAudio_UnregisterPlatformAudioUser(void* a0, void* a1) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; return EOS_NotConfigured; }
EOS_DECLARE_FUNC(void) EOS_RTCAudio_UnregisterPlatformUser(void* a0, void* a1, void* a2, void* a3) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; (void)a2; (void)a3; }
EOS_DECLARE_FUNC(void) EOS_RTCAudio_UpdateReceivingVolume(void* a0, void* a1, void* a2, void* a3) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; (void)a2; (void)a3; }
EOS_DECLARE_FUNC(void) EOS_RTCAudio_UpdateSendingVolume(void* a0, void* a1, void* a2, void* a3) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; (void)a1; (void)a2; (void)a3; }

/* Release fns the generator regex skipped — generic 1-arg stubs. */
EOS_DECLARE_FUNC(void) EOS_Achievements_UnlockedAchievement_Release(void* a0) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; }
EOS_DECLARE_FUNC(void) EOS_Leaderboards_LeaderboardDefinition_Release(void* a0) { EOS_LOG_WARN("STUB: %s", __func__); (void)a0; }
